### ISSUE TITLE
我在 Win10 上跑不起来

### ISSUE THREAD

**Issue by chehan01** [ForkFG/TerminalXbqg#16]
能出一个在win10上运行的说明书吗，谢谢了

**Comment by ForkKILLET** [comment]
详细说说哪里跑不起来

**Comment by ForkKILLET** [comment]
限于我手头没有 Win10 机子，现在只能提供一些文字上的帮助。  

先确认一些情况：
[这里](https://github.com/ForkKILLET/TerminalXbqg/blob/master/ReadMe.zh-Hans.md#%E5%AE%89%E8%A3%85) 所写的安装步骤请问您进行到了哪一步？出了什么问题？  
您是在 Win10 的什么终端下运行脚本的？

---

并未实证可行但我觉得靠谱的建议：
1. 在 Win10 应用商店下载安装 `Windows Terminal`（如果出于某些原因下载不了，以下命令可以在 powershell 中执行）。
2. 如果您还没有安装 `git`, `yarn / npm`, `node` 这些程序，可以通过 chocolatey 快速安装
   1. 从[官网](https://chocolatey.org/install) 复制安装命令（在 powershell 中运行）
      ```powershell
      Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      ```
   2. chocolatey 安装完之后，执行 `choco install -y git yarn nodejs`。
3. 执行 `git clone https://github.com/ForkKILLET/TerminalXbqg` 以克隆本仓库。（如果显示找不到 `git` 命令，重启终端）
4. 进入克隆到的目录（如 `cd TerminalXbqg`），执行 `yarn` 以安装脚本需要的依赖。
5. 执行 `node main.js` 运行脚本。

---

PS：
回复可以 at 我，以便更快收到（不过最近我会盯着这个帖子的，自己写的东西有人用了也是很开心的事情）

**Comment by chehan01** [comment]
> 限于我手头没有 Win10 机子，现在只能提供一些文字上的帮助。
> 
> 先确认一些情况： [这里](https://github.com/ForkKILLET/TerminalXbqg/blob/master/ReadMe.zh-Hans.md#%E5%AE%89%E8%A3%85) 所写的安装步骤请问您进行到了哪一步？出了什么问题？ 您是在 Win10 的什么终端下运行脚本的？
> 
> 并未实证可行但我觉得靠谱的建议：
> 
> 1. 在 Win10 应用商店下载安装 `Windows Terminal`（如果出于某些原因下载不了，以下命令可以在 powershell 中执行）。
> 2. 如果您还没有安装 `git`, `yarn / npm`, `node` 这些程序，可以通过 chocolatey 快速安装
>    
>    1. 从[官网](https://chocolatey.org/install) 复制安装命令（在 powershell 中运行）
>       ```powershell
>       Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
>       ```
>    2. chocolatey 安装完之后，执行 `choco install -y git yarn nodejs`。
> 3. 执行 `git clone https://github.com/ForkKILLET/TerminalXbqg` 以克隆本仓库。（如果显示找不到 `git` 命令，重启终端）
> 4. 进入克隆到的目录（如 `cd TerminalXbqg`），执行 `yarn` 以安装脚本需要的依赖。
> 5. 执行 `node main.js` 运行脚本。
> 
> PS： 回复可以 at 我，以便更快收到（不过最近我会盯着这个帖子的，自己写的东西有人用了也是很开心的事情）

谢谢回复，我昨天能够跑起来了，但是我一直没有搞懂，我该从哪添加书？ @ForkΨKillet

**Comment by chehan01** [comment]
> 限于我手头没有 Win10 机子，现在只能提供一些文字上的帮助。
> 
> 先确认一些情况： [这里](https://github.com/ForkKILLET/TerminalXbqg/blob/master/ReadMe.zh-Hans.md#%E5%AE%89%E8%A3%85) 所写的安装步骤请问您进行到了哪一步？出了什么问题？ 您是在 Win10 的什么终端下运行脚本的？
> 
> 并未实证可行但我觉得靠谱的建议：
> 
> 1. 在 Win10 应用商店下载安装 `Windows Terminal`（如果出于某些原因下载不了，以下命令可以在 powershell 中执行）。
> 2. 如果您还没有安装 `git`, `yarn / npm`, `node` 这些程序，可以通过 chocolatey 快速安装
>    
>    1. 从[官网](https://chocolatey.org/install) 复制安装命令（在 powershell 中运行）
>       ```powershell
>       Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
>       ```
>    2. chocolatey 安装完之后，执行 `choco install -y git yarn nodejs`。
> 3. 执行 `git clone https://github.com/ForkKILLET/TerminalXbqg` 以克隆本仓库。（如果显示找不到 `git` 命令，重启终端）
> 4. 进入克隆到的目录（如 `cd TerminalXbqg`），执行 `yarn` 以安装脚本需要的依赖。
> 5. 执行 `node main.js` 运行脚本。
> 
> PS： 回复可以 at 我，以便更快收到（不过最近我会盯着这个帖子的，自己写的东西有人用了也是很开心的事情）

谢谢回复，我昨天能够跑起来了，但是我一直没有搞懂，我该从哪添加书？ @ForkΨKillet

**Comment by ForkKILLET** [comment]
@chehan01 恭喜，加书的话您需要先用浏览器从某个源（就是看书的网站）打开你要看的书，把链接中书的 id 复制下来，然后 `xbqg fetch` 之。之后，您可能希望用 `xbqg book_mark` 添加书签防止丢失。

---

举例：
1. 选一个源（source）。您可以从 `xbqg config source.list` 看到源列表，目前不多，我个人用下来 ibiqu.net 质量比较高。  
2. 先 `xbqg source ibiqu` 切换到 ibiqu 源。（加入书签之后就可以省略这个步骤，我们有自动换源）
3. 比如你要看，呃，我从首页找一本好了比如《圣墟》，那你点击去到目录页，然后进第一章。这个时候地址是 `http://www.ibiqu.net/book/52542/20380548.htm` 你可以看到里面有一串数字就是 `52542/20380548`
4. `xbqg fetch 52542/20380548` 就行啦，现在可以关闭浏览器了。

**Comment by ForkKILLET** [comment]
另外 `xbqg i` 进入交互模式，体验会更好

**Comment by chehan01** [comment]
> 另外 `xbqg i` 进入交互模式，体验会更好

非常nice兄弟，谢谢，我已经get了，我非常愿意给你推广一下你的东西

**Comment by ForkKILLET** [comment]
噢谢谢！孩子乐坏了

我去改进一下教程，确实这个怎么添加书不太容易摸索。
